language: cpp

compiler: gcc
dist: trusty

sudo: true

addons:
  apt:
    packages:
    - git
    - dpkg-dev
    - make
    - g++
    - gcc
    - binutils
    - libx11-dev
    - libxpm-dev
    - libxft-dev
    - libxext-dev
    - libatomic-ops-dev

install:
    - cd ..
    - mkdir dependancies
    - cd dependancies
    - echo STARTING CLHEP BUILD `pwd`
    - git clone https://github.com/hyperk/CLHEP.git CLHEP
    - cd CLHEP/
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX= ../source/2.2.0.4/CLHEP
    - make -j8
    - sudo make install 
    - cd ../..
    - echo Geant4 BUILD `pwd`
    - wget http://geant4.web.cern.ch/geant4/support/source/geant4.10.01.p03.tar.gz
    - tar -zxf geant4.10.01.p03.tar.gz
    - cd geant4.10.01.p03
    - mkdir build
    - cd build
    - cmake -DGEANT4_INSTALL_DATA=ON -DGEANT4_INSTALL_DATADIR=./Data -DCMAKE_INSTALL_PREFIX=./install -DCLHEP_VERSION_OK=${CLHEP_VERSION} -DCLHEP_LIBRARIES= ./lib -DCLHEP_INCLUDE_DIRS= ./include ../
    - make -j8
    - sudo make install

install:
    - cd ..
    - mkdir dependancies
    - cd dependancies
    - wget https://cmake.org/files/v3.9/cmake-3.9.0.tar.gz  --no-check-certificate
    - tar zxf cmake-3.9.0.tar.gz
    - cd cmake-3.9.0/
    - sudo apt-get purge cmake
    - ./bootstrap
    - make -j8
    - sudo make install 
    - cd ..
    - echo STARTING ROOT BUILD `pwd`
    - wget https://root.cern.ch/download/root_v6.10.00.source.tar.gz
    - tar -zxf root_v6.10.00.source.tar.gz
    - cd root-6.10.00
    - mkdir Build
    - cd Build
    - cmake ../
    - make -j8 LLVMCore
    - make -j8 LLVMCore
    - make -j8 LLVMCore
    - make -j8 LLVMCore
    - make -j8 LLVMCore
    - make -j8 LLVMCore
    - make -j8 LLVMCore
    - make -j8 LLVMCore
    - sudo make install

script: true
