language: cpp

compiler: gcc
dist: trusty

sudo: true

addons:
  apt:
    packages:
    - git
    - dpkg-dev
    - make
    - g++
    - gcc
    - binutils
    - libx11-dev
    - libxpm-dev
    - libxft-dev
    - libxext-dev
    - libatomic-ops-dev

jobs:
  include:
    - stage: SETUP & CLHEP
      install:
        - ./CI.sh Setup
        - ./CI.sh CLHEP
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: Geant4
      install:
        - ./CI.sh Geant4
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: cmake
      install:
        - ./CI.sh cmake
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: root1
      install:
        - ./CI.sh root1
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: root2
      install:
        - ./CI.sh root2
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
   - stage: root3
      install:
        - ./CI.sh root3
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs