language: cpp

compiler: gcc
dist: trusty

addons:
  apt:
    packages:
    - git
    - dpkg-dev
    - make
    - g++
    - gcc
    - binutils
    - libx11-dev
    - libxpm-dev
    - libxft-dev
    - libxext-dev
    - libatomic-ops-dev
    - root-system

jobs:
  include:
    - stage: SETUP
      sudo: false
      script: ./CI.sh Setup
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/logs
    - stage: CLHEP
      sudo: false
      script: ./CI.sh CLHEP
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/logs
    - stage: Geant4
      sudo: false
      script: ./CI.sh Geant4
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/logs
    - stage: WCSim built
      sudo: true
      script: ./CI.sh build
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/logs