language: cpp	
	  
compile: gcc
dist: trusty	
      
sudo: false
	
addons:	
  apt:
  packages:
  - git	
  - dpkg-dev
  - make	
  - g++	
  - gcc	
  - binutils
  - libx11-dev
  - libxpm-dev
  - libxft-dev
  - libxext-dev
  - libatomic-ops-dev
  - libx11-6

install:
 - cd ..
  - mkdir dependancies
   - cd dependancies

install:
 - echo STARTING CLHEP BUILD `pwd`
 - git clone https://github.com/hyperk/CLHEP.git CLHEP
 - cd CLHEP/
 - mkdir build
 - cd build
 - cmake -DCMAKE_INSTALL_PREFIX= ../source/2.2.0.4/CLHEP
 - make -j8 
 - make install 	     
   

install:
 - cd ..
 - mkdir dependancies
 - cd dependancies
 - wget http://geant4.web.cern.ch/geant4/support/source/geant4.10.01.p03.tar.gz
 - tar -zxf geant4.10.01.p03.tar.gz
 - ls
 - cd geant4.10.01.p03
 - mkdir build
 - cd build


script: true
 