language: cpp

compiler: gcc
dist: trusty

addons:
  apt:
    packages:
    - git
    - dpkg-dev
    - make
    - g++
    - gcc
    - binutils
    - libx11-dev
    - libxpm-dev
    - libxft-dev
    - libxext-dev
    - libatomic-ops-dev

jobs:
  include:
    - stage: SETUP & CLHEP
      sudo: false
      install: ./CI.sh Setup; ./CI.sh CLHEP
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    -
      sudo: false
      install: ./CI.sh Geant4
      cache:
        directories:
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/logs
    -
      sudo: false
      install: ./CI.sh cmake
      cache:
        directories:
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/logs
    - stage: root1
      sudo: false
      install:
        - ./CI.sh root1
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: root2
      sudo: false
      install:
        - ./CI.sh root2
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: root3
      sudo: false
      install:
        - ./CI.sh root3
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: root4
      sudo: false
      install:
        - ./CI.sh root4
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: root5
      sudo: false
      install:
        - ./CI.sh root5
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs
    - stage: root6
      sudo: false
      install:
        - ./CI.sh root6
      script: true
      cache:
        directories:
            - /home/travis/dependancies/CLHEP
            - /home/travis/dependancies/geant4.10.01.p03
            - /home/travis/dependancies/cmake-3.9.0
            - /home/travis/dependancies/root-6.10.00
            - /home/travis/logs


